{
  "educator": "Солодовников Андрей Павлович",
  "groups": ["ИБ-31", "ИБ-32", "ИБ-33", "ИБ-34", "ИВТ-31", "ИВТ-32", "ИВТ-33", "ИВТ-34", "ИКТ-31", "ИКТ-32", "ИКТ-33", "ИКТ-34", "КТ-31", "ПИН-31", "ПИН-32", "ПИН-33", "ПИН-34", "ПМ-31", "ПМ-32", "ИВТ-14М", "ИВТ-24М", "ИВТ-31В", "ИВТ-31Д"],
  "semester_starts_at": '01-09-2025',
  "class_names_cast": {
    "Микропроцессорные средства и системы" : "МПСиС",
    "Микропроцессорные системы и средства" : "МПСиС",
    "Архитектура микропроцессорных систем и средств" : "МПСиС",
    "Вычислительная техника и информационные технологии" : "МПСиС",
    "Инструменты разработчика и основы функциональной верификации" : "ИРиОФВ",
    "Универсальная методология верификации (UVM)" : "UVM"
  },
  "repeat_number": 5, # число 4-недельных повторений
                      # (4 для 16-ти недель, 5 для добавления 17-18-ых недель)
}
